# Python and Data
This assignment will introduce you to using python and pandas inside a jupyter notebook for data exploration and manipulation.

1. Write the required python code to load the data file `temperature.csv` into a pandas dataframe.

In [17]:
import pandas as pd
pd.read_csv("temperature.csv")

                             date        nodeid  temperature
0       2018-07-15 00:00:02-05:00  001e0610b9e9        32.10
1       2018-07-15 00:00:02-05:00  001e0610e537        27.10
2       2018-07-15 00:00:03-05:00  001e0610ee61        26.70
3       2018-07-15 00:00:03-05:00  001e061135cb        25.40
4       2018-07-15 00:00:03-05:00  001e06113f54        53.20
5       2018-07-15 00:00:03-05:00  001e06115365        60.60
6       2018-07-15 00:00:04-05:00  001e061144be        52.80
7       2018-07-15 00:00:05-05:00  001e0610ee41        26.25
8       2018-07-15 00:00:05-05:00  001e0610ee43        24.80
9       2018-07-15 00:00:06-05:00  001e0610bc12        57.80
10      2018-07-15 00:00:06-05:00  001e0610e532        28.05
11      2018-07-15 00:00:07-05:00  001e0610f05c        26.20
12      2018-07-15 00:00:08-05:00  001e06113cf1        57.50
13      2018-07-15 00:00:08-05:00  001e061146cb        52.60
14      2018-07-15 00:00:09-05:00  001e06109416        46.20
15      2018-07-15 00:00:09-05:00  001e061130f4        26.20
16      2018-07-15 00:00:09-05:00  001e061144c0        54.30
17      2018-07-15 00:00:10-05:00  001e0610eef2        59.10
18      2018-07-15 00:00:10-05:00  001e06113ad8        56.10
19      2018-07-15 00:00:10-05:00  001e0611462f        49.30
20      2018-07-15 00:00:11-05:00  001e0610e835        50.80
21      2018-07-15 00:00:11-05:00  001e06113a48        43.50
22      2018-07-15 00:00:12-05:00  001e0610bbff        26.90
23      2018-07-15 00:00:12-05:00  001e0610e809        28.05
24      2018-07-15 00:00:13-05:00  001e0610e540        31.00
25      2018-07-15 00:00:13-05:00  001e0610ef27        26.20
26      2018-07-15 00:00:14-05:00  001e0610f730        27.65
27      2018-07-15 00:00:14-05:00  001e06113acb        52.80
28      2018-07-15 00:00:15-05:00  001e0611537d        49.60
29      2018-07-15 00:00:16-05:00  001e0610ee36        31.60
...                           ...           ...          ...
940282  2018-07-20 23:59:43-05:00  001e06113a48        39.00
940283  2018-07-20 23:59:44-05:00  001e06115365        55.40
940284  2018-07-20 23:59:45-05:00  001e06113cf1        53.60
940285  2018-07-20 23:59:47-05:00  001e0610b9e9        30.10
940286  2018-07-20 23:59:47-05:00  001e0610e835        48.20
940287  2018-07-20 23:59:47-05:00  001e061146d6        45.90
940288  2018-07-20 23:59:47-05:00  001e0611537d        44.90
940289  2018-07-20 23:59:48-05:00  001e0610e540        25.40
940290  2018-07-20 23:59:48-05:00  001e061135cb        21.45
940291  2018-07-20 23:59:49-05:00  001e0610bbff        22.69
940292  2018-07-20 23:59:49-05:00  001e0610ee82        22.20
940293  2018-07-20 23:59:49-05:00  001e0610f05c        23.50
940294  2018-07-20 23:59:50-05:00  001e06109f62        45.40
940295  2018-07-20 23:59:51-05:00  001e0610e532        23.40
940296  2018-07-20 23:59:51-05:00  001e0610e537        24.90
940297  2018-07-20 23:59:51-05:00  001e06113cff        53.20
940298  2018-07-20 23:59:51-05:00  001e06113d22        46.30
940299  2018-07-20 23:59:52-05:00  001e0610bbf9        16.10
940300  2018-07-20 23:59:52-05:00  001e061144c0        48.70
940301  2018-07-20 23:59:54-05:00  001e0610ba46        22.20
940302  2018-07-20 23:59:55-05:00  001e0610f730        23.55
940303  2018-07-20 23:59:56-05:00  001e0610ef27        23.20
940304  2018-07-20 23:59:57-05:00  001e0610ee5d        26.90
940305  2018-07-20 23:59:57-05:00  001e06113f54        52.10
940306  2018-07-20 23:59:58-05:00  001e0610bc12        53.30
940307  2018-07-20 23:59:59-05:00  001e0610ee36        24.40
940308  2018-07-20 23:59:59-05:00  001e0610eef4        24.20
940309  2018-07-20 23:59:59-05:00  001e061130f4        20.80
940310  2018-07-20 23:59:59-05:00  001e0611536c        44.50
940311  2018-07-21 00:00:00-05:00  001e0610ef73        28.70

[940312 rows x 3 columns]

2. Write the required python code display the first 10 values of your dataframe.

In [18]:
df = pd.read_csv("temperature.csv")
df.iloc[0:10]

                        date        nodeid  temperature
0  2018-07-15 00:00:02-05:00  001e0610b9e9        32.10
1  2018-07-15 00:00:02-05:00  001e0610e537        27.10
2  2018-07-15 00:00:03-05:00  001e0610ee61        26.70
3  2018-07-15 00:00:03-05:00  001e061135cb        25.40
4  2018-07-15 00:00:03-05:00  001e06113f54        53.20
5  2018-07-15 00:00:03-05:00  001e06115365        60.60
6  2018-07-15 00:00:04-05:00  001e061144be        52.80
7  2018-07-15 00:00:05-05:00  001e0610ee41        26.25
8  2018-07-15 00:00:05-05:00  001e0610ee43        24.80
9  2018-07-15 00:00:06-05:00  001e0610bc12        57.80

3. Write the required python code to `describe` your dataframe, this will show the count, mean, standard deviation, minimum and maximum value, as well as the percentiles (0.25, 0.5, 0.75) for the temperature column.

In [19]:
df.temperature.describe()

count    940312.000000
mean         39.290672
std          12.962963
min          15.800000
25%          27.200000
50%          35.300000
75%          51.300000
max          68.500000
Name: temperature, dtype: float64

4. Write the required python code to rename the "temperature" column to "Tc".

In [20]:
df.rename(columns={'temperature':'Tc'})

                             date        nodeid     Tc
0       2018-07-15 00:00:02-05:00  001e0610b9e9  32.10
1       2018-07-15 00:00:02-05:00  001e0610e537  27.10
2       2018-07-15 00:00:03-05:00  001e0610ee61  26.70
3       2018-07-15 00:00:03-05:00  001e061135cb  25.40
4       2018-07-15 00:00:03-05:00  001e06113f54  53.20
5       2018-07-15 00:00:03-05:00  001e06115365  60.60
6       2018-07-15 00:00:04-05:00  001e061144be  52.80
7       2018-07-15 00:00:05-05:00  001e0610ee41  26.25
8       2018-07-15 00:00:05-05:00  001e0610ee43  24.80
9       2018-07-15 00:00:06-05:00  001e0610bc12  57.80
10      2018-07-15 00:00:06-05:00  001e0610e532  28.05
11      2018-07-15 00:00:07-05:00  001e0610f05c  26.20
12      2018-07-15 00:00:08-05:00  001e06113cf1  57.50
13      2018-07-15 00:00:08-05:00  001e061146cb  52.60
14      2018-07-15 00:00:09-05:00  001e06109416  46.20
15      2018-07-15 00:00:09-05:00  001e061130f4  26.20
16      2018-07-15 00:00:09-05:00  001e061144c0  54.30
17      2018-07-15 00:00:10-05:00  001e0610eef2  59.10
18      2018-07-15 00:00:10-05:00  001e06113ad8  56.10
19      2018-07-15 00:00:10-05:00  001e0611462f  49.30
20      2018-07-15 00:00:11-05:00  001e0610e835  50.80
21      2018-07-15 00:00:11-05:00  001e06113a48  43.50
22      2018-07-15 00:00:12-05:00  001e0610bbff  26.90
23      2018-07-15 00:00:12-05:00  001e0610e809  28.05
24      2018-07-15 00:00:13-05:00  001e0610e540  31.00
25      2018-07-15 00:00:13-05:00  001e0610ef27  26.20
26      2018-07-15 00:00:14-05:00  001e0610f730  27.65
27      2018-07-15 00:00:14-05:00  001e06113acb  52.80
28      2018-07-15 00:00:15-05:00  001e0611537d  49.60
29      2018-07-15 00:00:16-05:00  001e0610ee36  31.60
...                           ...           ...    ...
940282  2018-07-20 23:59:43-05:00  001e06113a48  39.00
940283  2018-07-20 23:59:44-05:00  001e06115365  55.40
940284  2018-07-20 23:59:45-05:00  001e06113cf1  53.60
940285  2018-07-20 23:59:47-05:00  001e0610b9e9  30.10
940286  2018-07-20 23:59:47-05:00  001e0610e835  48.20
940287  2018-07-20 23:59:47-05:00  001e061146d6  45.90
940288  2018-07-20 23:59:47-05:00  001e0611537d  44.90
940289  2018-07-20 23:59:48-05:00  001e0610e540  25.40
940290  2018-07-20 23:59:48-05:00  001e061135cb  21.45
940291  2018-07-20 23:59:49-05:00  001e0610bbff  22.69
940292  2018-07-20 23:59:49-05:00  001e0610ee82  22.20
940293  2018-07-20 23:59:49-05:00  001e0610f05c  23.50
940294  2018-07-20 23:59:50-05:00  001e06109f62  45.40
940295  2018-07-20 23:59:51-05:00  001e0610e532  23.40
940296  2018-07-20 23:59:51-05:00  001e0610e537  24.90
940297  2018-07-20 23:59:51-05:00  001e06113cff  53.20
940298  2018-07-20 23:59:51-05:00  001e06113d22  46.30
940299  2018-07-20 23:59:52-05:00  001e0610bbf9  16.10
940300  2018-07-20 23:59:52-05:00  001e061144c0  48.70
940301  2018-07-20 23:59:54-05:00  001e0610ba46  22.20
940302  2018-07-20 23:59:55-05:00  001e0610f730  23.55
940303  2018-07-20 23:59:56-05:00  001e0610ef27  23.20
940304  2018-07-20 23:59:57-05:00  001e0610ee5d  26.90
940305  2018-07-20 23:59:57-05:00  001e06113f54  52.10
940306  2018-07-20 23:59:58-05:00  001e0610bc12  53.30
940307  2018-07-20 23:59:59-05:00  001e0610ee36  24.40
940308  2018-07-20 23:59:59-05:00  001e0610eef4  24.20
940309  2018-07-20 23:59:59-05:00  001e061130f4  20.80
940310  2018-07-20 23:59:59-05:00  001e0611536c  44.50
940311  2018-07-21 00:00:00-05:00  001e0610ef73  28.70

[940312 rows x 3 columns]

5. Write the required python code to add a new column to the dataframe that represents the equivalent temperature value in fahrenheit, you will now three columns in your dataframe. One will represent the date, the celsius value (Tc) and fahrenheit (Tf).

In [21]:
df['Tf']=df['temperature']*1.8+32
df.rename(columns = {'temperature':'Tc'})

                             date        nodeid     Tc       Tf
0       2018-07-15 00:00:02-05:00  001e0610b9e9  32.10   89.780
1       2018-07-15 00:00:02-05:00  001e0610e537  27.10   80.780
2       2018-07-15 00:00:03-05:00  001e0610ee61  26.70   80.060
3       2018-07-15 00:00:03-05:00  001e061135cb  25.40   77.720
4       2018-07-15 00:00:03-05:00  001e06113f54  53.20  127.760
5       2018-07-15 00:00:03-05:00  001e06115365  60.60  141.080
6       2018-07-15 00:00:04-05:00  001e061144be  52.80  127.040
7       2018-07-15 00:00:05-05:00  001e0610ee41  26.25   79.250
8       2018-07-15 00:00:05-05:00  001e0610ee43  24.80   76.640
9       2018-07-15 00:00:06-05:00  001e0610bc12  57.80  136.040
10      2018-07-15 00:00:06-05:00  001e0610e532  28.05   82.490
11      2018-07-15 00:00:07-05:00  001e0610f05c  26.20   79.160
12      2018-07-15 00:00:08-05:00  001e06113cf1  57.50  135.500
13      2018-07-15 00:00:08-05:00  001e061146cb  52.60  126.680
14      2018-07-15 00:00:09-05:00  001e06109416  46.20  115.160
15      2018-07-15 00:00:09-05:00  001e061130f4  26.20   79.160
16      2018-07-15 00:00:09-05:00  001e061144c0  54.30  129.740
17      2018-07-15 00:00:10-05:00  001e0610eef2  59.10  138.380
18      2018-07-15 00:00:10-05:00  001e06113ad8  56.10  132.980
19      2018-07-15 00:00:10-05:00  001e0611462f  49.30  120.740
20      2018-07-15 00:00:11-05:00  001e0610e835  50.80  123.440
21      2018-07-15 00:00:11-05:00  001e06113a48  43.50  110.300
22      2018-07-15 00:00:12-05:00  001e0610bbff  26.90   80.420
23      2018-07-15 00:00:12-05:00  001e0610e809  28.05   82.490
24      2018-07-15 00:00:13-05:00  001e0610e540  31.00   87.800
25      2018-07-15 00:00:13-05:00  001e0610ef27  26.20   79.160
26      2018-07-15 00:00:14-05:00  001e0610f730  27.65   81.770
27      2018-07-15 00:00:14-05:00  001e06113acb  52.80  127.040
28      2018-07-15 00:00:15-05:00  001e0611537d  49.60  121.280
29      2018-07-15 00:00:16-05:00  001e0610ee36  31.60   88.880
...                           ...           ...    ...      ...
940282  2018-07-20 23:59:43-05:00  001e06113a48  39.00  102.200
940283  2018-07-20 23:59:44-05:00  001e06115365  55.40  131.720
940284  2018-07-20 23:59:45-05:00  001e06113cf1  53.60  128.480
940285  2018-07-20 23:59:47-05:00  001e0610b9e9  30.10   86.180
940286  2018-07-20 23:59:47-05:00  001e0610e835  48.20  118.760
940287  2018-07-20 23:59:47-05:00  001e061146d6  45.90  114.620
940288  2018-07-20 23:59:47-05:00  001e0611537d  44.90  112.820
940289  2018-07-20 23:59:48-05:00  001e0610e540  25.40   77.720
940290  2018-07-20 23:59:48-05:00  001e061135cb  21.45   70.610
940291  2018-07-20 23:59:49-05:00  001e0610bbff  22.69   72.842
940292  2018-07-20 23:59:49-05:00  001e0610ee82  22.20   71.960
940293  2018-07-20 23:59:49-05:00  001e0610f05c  23.50   74.300
940294  2018-07-20 23:59:50-05:00  001e06109f62  45.40  113.720
940295  2018-07-20 23:59:51-05:00  001e0610e532  23.40   74.120
940296  2018-07-20 23:59:51-05:00  001e0610e537  24.90   76.820
940297  2018-07-20 23:59:51-05:00  001e06113cff  53.20  127.760
940298  2018-07-20 23:59:51-05:00  001e06113d22  46.30  115.340
940299  2018-07-20 23:59:52-05:00  001e0610bbf9  16.10   60.980
940300  2018-07-20 23:59:52-05:00  001e061144c0  48.70  119.660
940301  2018-07-20 23:59:54-05:00  001e0610ba46  22.20   71.960
940302  2018-07-20 23:59:55-05:00  001e0610f730  23.55   74.390
940303  2018-07-20 23:59:56-05:00  001e0610ef27  23.20   73.760
940304  2018-07-20 23:59:57-05:00  001e0610ee5d  26.90   80.420
940305  2018-07-20 23:59:57-05:00  001e06113f54  52.10  125.780
940306  2018-07-20 23:59:58-05:00  001e0610bc12  53.30  127.940
940307  2018-07-20 23:59:59-05:00  001e0610ee36  24.40   75.920
940308  2018-07-20 23:59:59-05:00  001e0610eef4  24.20   75.560
940309  2018-07-20 23:59:59-05:00  001e061130f4  20.80   69.440
940310  2018-07-20 23:59:59-05:00  001e0611536c  44.50  112.100
940311  2018-07-21 00:00:00-05:00  001e0610ef73  28.70   83.660

[940312 rows x 4 columns]

6. Given the values of temperature, what can you say about the likely source of this data? Use the cell below to enter your answer, this will be text (you will need to convert the cell from code to markdown).

The source of data maybe grom a weather forecast centre as the temperature is organised by date and time.

7. Write the required python code to change the index for the dataframe from numerically indexed dataframe to one of date using the date column. Make sure you drop the date column once you have created new index.

In [22]:
df1 = df.set_index("date", drop=True)
df1

                                 nodeid  temperature       Tf
date
2018-07-15 00:00:02-05:00  001e0610b9e9        32.10   89.780
2018-07-15 00:00:02-05:00  001e0610e537        27.10   80.780
2018-07-15 00:00:03-05:00  001e0610ee61        26.70   80.060
2018-07-15 00:00:03-05:00  001e061135cb        25.40   77.720
2018-07-15 00:00:03-05:00  001e06113f54        53.20  127.760
2018-07-15 00:00:03-05:00  001e06115365        60.60  141.080
2018-07-15 00:00:04-05:00  001e061144be        52.80  127.040
2018-07-15 00:00:05-05:00  001e0610ee41        26.25   79.250
2018-07-15 00:00:05-05:00  001e0610ee43        24.80   76.640
2018-07-15 00:00:06-05:00  001e0610bc12        57.80  136.040
2018-07-15 00:00:06-05:00  001e0610e532        28.05   82.490
2018-07-15 00:00:07-05:00  001e0610f05c        26.20   79.160
2018-07-15 00:00:08-05:00  001e06113cf1        57.50  135.500
2018-07-15 00:00:08-05:00  001e061146cb        52.60  126.680
2018-07-15 00:00:09-05:00  001e06109416        46.20  115.160
2018-07-15 00:00:09-05:00  001e061130f4        26.20   79.160
2018-07-15 00:00:09-05:00  001e061144c0        54.30  129.740
2018-07-15 00:00:10-05:00  001e0610eef2        59.10  138.380
2018-07-15 00:00:10-05:00  001e06113ad8        56.10  132.980
2018-07-15 00:00:10-05:00  001e0611462f        49.30  120.740
2018-07-15 00:00:11-05:00  001e0610e835        50.80  123.440
2018-07-15 00:00:11-05:00  001e06113a48        43.50  110.300
2018-07-15 00:00:12-05:00  001e0610bbff        26.90   80.420
2018-07-15 00:00:12-05:00  001e0610e809        28.05   82.490
2018-07-15 00:00:13-05:00  001e0610e540        31.00   87.800
2018-07-15 00:00:13-05:00  001e0610ef27        26.20   79.160
2018-07-15 00:00:14-05:00  001e0610f730        27.65   81.770
2018-07-15 00:00:14-05:00  001e06113acb        52.80  127.040
2018-07-15 00:00:15-05:00  001e0611537d        49.60  121.280
2018-07-15 00:00:16-05:00  001e0610ee36        31.60   88.880
...                                 ...          ...      ...
2018-07-20 23:59:43-05:00  001e06113a48        39.00  102.200
2018-07-20 23:59:44-05:00  001e06115365        55.40  131.720
2018-07-20 23:59:45-05:00  001e06113cf1        53.60  128.480
2018-07-20 23:59:47-05:00  001e0610b9e9        30.10   86.180
2018-07-20 23:59:47-05:00  001e0610e835        48.20  118.760
2018-07-20 23:59:47-05:00  001e061146d6        45.90  114.620
2018-07-20 23:59:47-05:00  001e0611537d        44.90  112.820
2018-07-20 23:59:48-05:00  001e0610e540        25.40   77.720
2018-07-20 23:59:48-05:00  001e061135cb        21.45   70.610
2018-07-20 23:59:49-05:00  001e0610bbff        22.69   72.842
2018-07-20 23:59:49-05:00  001e0610ee82        22.20   71.960
2018-07-20 23:59:49-05:00  001e0610f05c        23.50   74.300
2018-07-20 23:59:50-05:00  001e06109f62        45.40  113.720
2018-07-20 23:59:51-05:00  001e0610e532        23.40   74.120
2018-07-20 23:59:51-05:00  001e0610e537        24.90   76.820
2018-07-20 23:59:51-05:00  001e06113cff        53.20  127.760
2018-07-20 23:59:51-05:00  001e06113d22        46.30  115.340
2018-07-20 23:59:52-05:00  001e0610bbf9        16.10   60.980
2018-07-20 23:59:52-05:00  001e061144c0        48.70  119.660
2018-07-20 23:59:54-05:00  001e0610ba46        22.20   71.960
2018-07-20 23:59:55-05:00  001e0610f730        23.55   74.390
2018-07-20 23:59:56-05:00  001e0610ef27        23.20   73.760
2018-07-20 23:59:57-05:00  001e0610ee5d        26.90   80.420
2018-07-20 23:59:57-05:00  001e06113f54        52.10  125.780
2018-07-20 23:59:58-05:00  001e0610bc12        53.30  127.940
2018-07-20 23:59:59-05:00  001e0610ee36        24.40   75.920
2018-07-20 23:59:59-05:00  001e0610eef4        24.20   75.560
2018-07-20 23:59:59-05:00  001e061130f4        20.80   69.440
2018-07-20 23:59:59-05:00  001e0611536c        44.50  112.100
2018-07-21 00:00:00-05:00  001e0610ef73        28.70   83.660

[940312 rows x 3 columns]

8. Write the required python code that will calculate the range of dates that this data covers.

In [23]:
minimum = min(df['date'])
maximum = max(df['date'])
print('The start date is: '+minimum+'\nThe end date is: '+maximum)

The start date is: 2018-07-15 00:00:02-05:00
The end date is: 2018-07-21 00:00:00-05:00

9. Write the required python code to describe (count, mean, standard deviation, minimum and maximum value, as well as the percentiles (0.25, 0.5, 0.75)) grouped by `nodeid`.

In [24]:
df.groupby('nodeid').describe()

                   Tf                                                  \
                count        mean       std     min      25%      50%
nodeid
001e06109416  20666.0  113.726480  5.007510  105.26  109.760  112.460
001e06109f62   8678.0  120.250611  3.840612  113.18  117.500  119.660
001e0610b9e9  20697.0   91.207824  4.480051   83.48   87.800   90.140
001e0610ba16   9417.0   82.695130  3.644018   76.37   80.240   81.500
001e0610ba46  20577.0   77.162260  4.699504   68.72   73.220   76.640
001e0610ba8f  20697.0   81.761393  4.942663   72.14   77.720   81.680
001e0610bbf9  20695.0   71.879772  5.783589   60.44   67.460   71.240
001e0610bbff  21261.0   80.333226  5.407226   71.06   76.118   79.646
001e0610bc10    556.0   85.037194  3.175542   80.42   81.680   84.920
001e0610bc12  20163.0  137.624711  5.344566  127.76  133.340  136.760
001e0610e532  21407.0   83.481596  5.531642   73.49   78.620   82.580
001e0610e537  20542.0   83.373868  4.798176   74.48   79.520   83.120
001e0610e540  21448.0   83.677542  4.985928   75.29   79.340   82.670
001e0610e809  11739.0   82.233837  5.265560   73.04   78.512   82.220
001e0610e835  20232.0  124.564075  4.731926  116.60  120.560  123.800
001e0610ee33  21588.0   81.263260  4.985305   71.78   77.360   80.780
001e0610ee36  20694.0   88.701792  6.458761   75.92   83.660   87.980
001e0610ee41  21265.0   80.800820  4.926887   71.24   76.910   80.150
001e0610ee43  20645.0   76.499897  4.924748   67.46   71.600   77.000
001e0610ee5d  19953.0   86.483843  5.699838   71.24   81.860   85.640
001e0610ee61   1326.0   81.107163  2.652420   76.82   79.160   80.600
001e0610ee82  16234.0   77.461106  4.845312   70.16   74.012   76.280
001e0610eef2  20605.0  137.941736  4.740848  129.74  134.060  137.480
001e0610eef4  21472.0   80.254589  5.485896   70.70   75.650   79.790
001e0610ef27  21484.0   81.078955  5.592732   72.14   76.460   80.240
001e0610ef73  21580.0   83.135685  1.367949   79.88   82.220   83.120
001e0610f05c  20568.0   80.379673  5.282496   71.42   75.740   79.880
001e0610f703   6079.0  132.328163  2.720419  127.76  129.560  132.440
001e0610f730  21478.0   81.393958  5.119130   72.95   77.360   80.600
001e0610fb4c  17962.0   80.513670  4.968385   71.06   76.820   80.060
001e061130f4  20685.0   75.904450  5.417702   66.56   71.420   75.200
001e06113107   5553.0   96.212091  5.868144   87.08   91.220   94.460
001e061135cb  21577.0   79.285604  5.956176   69.35   74.660   78.170
001e06113a48  20208.0  109.312138  4.973741  101.12  105.440  108.320
001e06113acb  20648.0  128.955612  5.120055  120.56  124.520  128.120
001e06113ad8  20554.0  134.551169  4.897662  125.96  130.640  133.520
001e06113cf1  20537.0  134.049807  4.212576  126.32  130.460  133.520
001e06113cff   1335.0  129.044674  1.500008  126.50  127.940  128.660
001e06113d22  18173.0  123.282147  5.505173  114.80  118.760  122.000
001e06113dbc  20507.0  122.070501  4.524567  114.44  118.220  121.640
001e06113f54  20672.0  129.096068  3.843975  121.64  125.960  128.660
001e0611441e  20694.0  116.709284  5.289699  106.88  112.460  115.880
001e061144be  20687.0  126.904054  4.825311  116.96  122.720  127.040
001e061144c0  20639.0  128.784166  5.137864  118.94  124.700  128.300
001e06114500  12488.0  122.149154  4.262322  114.98  119.120  121.460
001e0611462f  20693.0  122.263576  4.944266  114.44  117.680  121.820
001e061146ba  20128.0  115.624854  5.397499  104.36  111.200  115.340
001e061146cb  20663.0  125.804383  4.862121  117.14  122.180  125.060
001e061146d6  20651.0  119.993877  4.790954  112.10  116.060  118.940
001e06115365  20612.0  140.268489  5.559709  130.10  135.680  140.180
001e0611536c  20693.0  117.786166  4.541948  109.94  113.720  117.320
001e0611537d  20207.0  121.002905  4.800584  112.46  116.960  120.740

                               temperature                                     \
                  75%      max       count       mean       std    min    25%
nodeid
001e06109416  118.040  127.400     20666.0  45.403600  2.781950  40.70  43.20
001e06109f62  122.720  129.920      8678.0  49.028117  2.133673  45.10  47.50
001e0610b9e9   95.180  104.000     20697.0  32.893236  2.488917  28.60  31.00
001e0610ba16   84.290   93.200      9417.0  28.163961  2.024455  24.65  26.80
001e0610ba46   81.140   88.520     20577.0  25.090144  2.610836  20.40  22.90
001e0610ba8f   85.100   96.170     20697.0  27.645218  2.745924  22.30  25.40
001e0610bbf9   75.920   88.160     20695.0  22.155429  3.213105  15.80  19.70
001e0610bbff   84.362   95.522     21261.0  26.851792  3.004015  21.70  24.51
001e0610bc10   88.340   89.960       556.0  29.465108  1.764190  26.90  27.60
001e0610bc12  141.440  153.140     20163.0  58.680395  2.969204  53.20  56.30
001e0610e532   88.340   97.700     21407.0  28.600887  3.073135  23.05  25.90
001e0610e537   86.900   99.500     20542.0  28.541038  2.665654  23.60  26.40
001e0610e540   87.800   97.520     21448.0  28.709745  2.769960  24.05  26.30
001e0610e809   86.450   93.200     11739.0  27.907687  2.925311  22.80  25.84
001e0610e835  128.300  139.100     20232.0  51.424486  2.628848  47.00  49.20
001e0610ee33   84.920   97.160     21588.0  27.368478  2.769614  22.10  25.20
001e0610ee36   93.380  106.340     20694.0  31.500995  3.588201  24.40  28.70
001e0610ee41   84.110   94.262     21265.0  27.111567  2.737160  21.80  24.95
001e0610ee43   80.060   89.240     20645.0  24.722165  2.735971  19.70  22.00
001e0610ee5d   91.400  100.760     19953.0  30.268802  3.166577  21.80  27.70
001e0610ee61   82.040   88.160      1326.0  27.281757  1.473567  24.90  26.20
001e0610ee82   80.060   93.200     16234.0  25.256170  2.691840  21.20  23.34
001e0610eef2  141.620  150.980     20605.0  58.856520  2.633804  54.30  56.70
001e0610eef4   84.740   95.162     21472.0  26.808105  3.047720  21.50  24.25
001e0610ef27   85.190   97.520     21484.0  27.266086  3.107074  22.30  24.70
001e0610ef73   84.110   89.420     21580.0  28.408714  0.759972  26.60  27.90
001e0610f05c   84.380   97.160     20568.0  26.877596  2.934720  21.90  24.30
001e0610f703  134.420  142.160      6079.0  55.737868  1.511344  53.20  54.20
001e0610f730   85.820   94.640     21478.0  27.441088  2.843961  22.75  25.20
001e0610fb4c   84.560   94.082     17962.0  26.952039  2.760214  21.70  24.90
001e061130f4   80.240   91.220     20685.0  24.391361  3.009835  19.20  21.90
001e06113107  101.120  112.820      5553.0  35.673384  3.260080  30.60  32.90
001e061135cb   84.020   95.000     21577.0  26.269780  3.308987  20.75  23.70
001e06113a48  113.540  123.800     20208.0  42.951188  2.763189  38.40  40.80
001e06113acb  132.980  144.680     20648.0  53.864229  2.844475  49.20  51.40
001e06113ad8  138.740  149.000     20554.0  56.972871  2.720923  52.20  54.80
001e06113cf1  137.660  144.500     20537.0  56.694337  2.340320  52.40  54.70
001e06113cff  129.920  134.060      1335.0  53.913708  0.833338  52.50  53.30
001e06113d22  127.940  136.940     18173.0  50.712304  3.058430  46.00  48.20
001e06113dbc  125.420  135.500     20507.0  50.039167  2.513649  45.80  47.90
001e06113f54  132.440  141.620     20672.0  53.942260  2.135542  49.80  52.20
001e0611441e  121.100  130.100     20694.0  47.060713  2.938722  41.60  44.70
001e061144be  130.640  138.560     20687.0  52.724474  2.680728  47.20  50.40
001e061144c0  132.260  143.960     20639.0  53.768981  2.854369  48.30  51.50
001e06114500  124.340  133.880     12488.0  50.082864  2.367957  46.10  48.40
001e0611462f  126.320  136.040     20693.0  50.146431  2.746814  45.80  47.60
001e061146ba  120.020  130.100     20128.0  46.458252  2.998611  40.20  44.00
001e061146cb  129.740  140.180     20663.0  52.113546  2.701178  47.30  50.10
001e061146d6  124.160  135.680     20651.0  48.885487  2.661641  44.50  46.70
001e06115365  144.140  155.300     20612.0  60.149161  3.088727  54.50  57.60
001e0611536c  121.460  129.560     20693.0  47.658981  2.523305  43.30  45.40
001e0611537d  125.060  133.880     20207.0  49.446058  2.666991  44.70  47.20


                50%    75%    max
nodeid
001e06109416  44.70  47.80  53.00
001e06109f62  48.70  50.40  54.40
001e0610b9e9  32.30  35.10  40.00
001e0610ba16  27.50  29.05  34.00
001e0610ba46  24.80  27.30  31.40
001e0610ba8f  27.60  29.50  35.65
001e0610bbf9  21.80  24.40  31.20
001e0610bbff  26.47  29.09  35.29
001e0610bc10  29.40  31.30  32.20
001e0610bc12  58.20  60.80  67.30
001e0610e532  28.10  31.30  36.50
001e0610e537  28.40  30.50  37.50
001e0610e540  28.15  31.00  36.40
001e0610e809  27.90  30.25  34.00
001e0610e835  51.00  53.50  59.50
001e0610ee33  27.10  29.40  36.20
001e0610ee36  31.10  34.10  41.30
001e0610ee41  26.75  28.95  34.59
001e0610ee43  25.00  26.70  31.80
001e0610ee5d  29.80  33.00  38.20
001e0610ee61  27.00  27.80  31.20
001e0610ee82  24.60  26.70  34.00
001e0610eef2  58.60  60.90  66.10
001e0610eef4  26.55  29.30  35.09
001e0610ef27  26.80  29.55  36.40
001e0610ef73  28.40  28.95  31.90
001e0610f05c  26.60  29.10  36.20
001e0610f703  55.80  56.90  61.20
001e0610f730  27.00  29.90  34.80
001e0610fb4c  26.70  29.20  34.49
001e061130f4  24.00  26.80  32.90
001e06113107  34.70  38.40  44.90
001e061135cb  25.65  28.90  35.00
001e06113a48  42.40  45.30  51.00
001e06113acb  53.40  56.10  62.60
001e06113ad8  56.40  59.30  65.00
001e06113cf1  56.40  58.70  62.50
001e06113cff  53.70  54.40  56.70
001e06113d22  50.00  53.30  58.30
001e06113dbc  49.80  51.90  57.50
001e06113f54  53.70  55.80  60.90
001e0611441e  46.60  49.50  54.50
001e061144be  52.80  54.80  59.20
001e061144c0  53.50  55.70  62.20
001e06114500  49.70  51.30  56.60
001e0611462f  49.90  52.40  57.80
001e061146ba  46.30  48.90  54.50
001e061146cb  51.70  54.30  60.10
001e061146d6  48.30  51.20  57.60
001e06115365  60.10  62.30  68.50
001e0611536c  47.40  49.70  54.20
001e0611537d  49.30  51.70  56.60

10. Pick a node (e.g. *nodeid* = 001e061146ba) and write the required python code to extract the data for that node from the larger dataframe, display the last 10 items.

In [56]:
df[df['nodeid'].str.contains('001e06113cff')].tail(10)

              date        nodeid  temperature      Tf
939890  2018-07-21  001e06113cff         52.9  127.22
939935  2018-07-21  001e06113cff         53.0  127.40
939978  2018-07-21  001e06113cff         53.0  127.40
940024  2018-07-21  001e06113cff         53.1  127.58
940068  2018-07-21  001e06113cff         53.2  127.76
940115  2018-07-21  001e06113cff         53.4  128.12
940160  2018-07-21  001e06113cff         53.5  128.30
940207  2018-07-21  001e06113cff         53.5  128.30
940254  2018-07-21  001e06113cff         53.2  127.76
940297  2018-07-21  001e06113cff         53.2  127.76

11.Write the required python code to resample the data of the single node returning the mean (average) for each day.

In [54]:
from pandas import datetime
from pandas import read_csv
df['date']=pd.to_datetime(df['date']).dt.date
a = df.groupby(['date','nodeid']).mean()
print(a)

                         temperature          Tf
date       nodeid
2018-07-15 001e06109416    47.646498  117.763696
           001e0610b9e9    34.483706   94.070670
           001e0610ba46    26.781724   80.207104
           001e0610ba8f    29.233104   84.619587
           001e0610bbf9    25.015928   77.028671
           001e0610bbff    29.557837   85.204107
           001e0610bc12    61.590476  142.862857
           001e0610e532    31.060028   87.908051
           001e0610e537    29.864797   85.756635
           001e0610e540    31.119730   88.015515
           001e0610e809    29.364532   84.856157
           001e0610e835    53.086500  127.555699
           001e0610ee33    29.185736   84.534325
           001e0610ee36    34.550293   94.190527
           001e0610ee41    29.576369   85.237464
           001e0610ee43    26.615517   79.907931
           001e0610ee5d    33.437015   92.186627
           001e0610ee61    27.281757   81.107163
           001e0610eef2    60.771744  141.389139
           001e0610eef4    30.014195   86.025551
           001e0610ef27    30.206118   86.371012
           001e0610ef73    28.145251   82.661452
           001e0610f05c    28.785109   83.813196
           001e0610f730    29.925629   85.866133
           001e0610fb4c    28.907431   84.033377
           001e061130f4    26.908648   80.435566
           001e061135cb    29.553044   85.195480
           001e06113a48    45.310615  113.559107
           001e06113acb    56.155503  133.079905
           001e06113ad8    59.263232  138.673818
...                              ...         ...
2018-07-21 001e0610ee43    21.499581   70.699246
           001e0610ee5d    26.552241   79.794034
           001e0610ee82    23.450814   74.211466
           001e0610eef2    55.452235  131.814022
           001e0610eef4    23.572286   74.430115
           001e0610ef27    23.991098   75.183976
           001e0610ef73    28.510479   83.318863
           001e0610f05c    23.561259   74.410266
           001e0610f730    23.631219   74.536195
           001e061130f4    20.198192   68.356745
           001e061135cb    22.203191   71.965744
           001e06113a48    39.354701  102.838462
           001e06113acb    49.846508  121.723715
           001e06113ad8    54.497075  130.094735
           001e06113cf1    55.040112  131.072202
           001e06113cff    53.454443  128.217997
           001e06113d22    46.704451  116.068012
           001e06113dbc    46.680056  116.024101
           001e06113f54    51.851253  125.332256
           001e0611441e    42.398329  108.316992
           001e061144be    48.364624  119.056323
           001e061144c0    49.035605  120.264089
           001e06114500    46.988982  116.580167
           001e0611462f    47.150139  116.870251
           001e061146ba    42.306724  108.152103
           001e061146cb    49.644073  121.359331
           001e061146d6    45.948954  114.708117
           001e06115365    55.420781  131.757406
           001e0611536c    44.965508  112.937914
           001e0611537d    45.656268  114.181282

[327 rows x 2 columns]

12. How many days worth of data is produced in the resampling? (you will need to convert the cell from code to markdown)

Looking above it seems 2days worth of data is produced in the sampling.

13. Write the required python code to resample the data of the single node returning the mean for each hour, display the first 24 values.

---
# Switching Dataset (London Air - www.londonair.org.uk)
Exploration of data that has potential problems.
BG1 == Barking and Dagenham - Rush Green
BQ7 == Bexley - Belvedere West
Date: January 01, 2017 - February 01, 2017

This data represents rainfall measurements at two locations within London and is measured in millimeters (mm).

I have **modified** this data for purpose of learning (that is I introduced errors).

14. Write the required python code to load the new dataset `london-rain.csv` for exploration, then using  `describe()` function what can you say about the data (enter your written answer in cell below your code, you will need to add a cell and change the cell type to markdown).

In [43]:
import pandas as pd1;
df1=pd1.read_csv('london-rain.csv')
df1.describe()

           0.00000
count  5948.000000
mean      1.670309
std      41.034861
min      -1.000000
25%       0.000000
50%       0.000000
75%       0.000000
max    2000.000000

15. You should have noticed that there are no headers associated with the data, write the required python code to add appropriate headers to data (site, variable, date, value, units, type) and display the result of the `describe` function.

In [44]:
df1.columns=("site","variable","date","value","units","type")
df1

     site variable              date  value units type
0     BG1     RAIN  01/01/2017 00:15    0.0    mm    P
1     BG1     RAIN  01/01/2017 00:30    0.0    mm    P
2     BG1     RAIN  01/01/2017 00:45    0.0    mm    P
3     BG1     RAIN  01/01/2017 01:00    0.0    mm    P
4     BG1     RAIN  01/01/2017 01:15    0.0    mm    P
5     BG1     RAIN  01/01/2017 01:30    0.0    mm    P
6     BG1     RAIN  01/01/2017 01:45    0.0    mm    P
7     BG1     RAIN  01/01/2017 02:00    0.0    mm    P
8     BG1     RAIN  01/01/2017 02:15    0.0    mm    P
9     BG1     RAIN  01/01/2017 02:30    0.0    mm    P
10    BG1     RAIN  01/01/2017 02:45    0.0    mm    P
11    BG1     RAIN  01/01/2017 03:00    0.0    mm    P
12    BG1     RAIN  01/01/2017 03:15    0.0    mm    P
13    BG1     RAIN  01/01/2017 03:30    0.0    mm    P
14    BG1     RAIN  01/01/2017 03:45    0.0    mm    P
15    BG1     RAIN  01/01/2017 04:00    0.0    mm    P
16    BG1     RAIN  01/01/2017 04:15    0.0    mm    P
17    BG1     RAIN  01/01/2017 04:30    0.0    mm    P
18    BG1     RAIN  01/01/2017 04:45    0.0    mm    P
19    BG1     RAIN  01/01/2017 05:00    0.0    mm    P
20    BG1     RAIN  01/01/2017 05:15    0.0    mm    P
21    BG1     RAIN  01/01/2017 05:30    0.0    mm    P
22    BG1     RAIN  01/01/2017 05:45    0.0    mm    P
23    BG1     RAIN  01/01/2017 06:00    0.0    mm    P
24    BG1     RAIN  01/01/2017 06:15    0.0    mm    P
25    BG1     RAIN  01/01/2017 06:30    0.0    mm    P
26    BG1     RAIN  01/01/2017 06:45    0.0    mm    P
27    BG1     RAIN  01/01/2017 07:00    0.0    mm    P
28    BG1     RAIN  01/01/2017 07:15    0.0    mm    P
29    BG1     RAIN  01/01/2017 07:30    0.0    mm    P
...   ...      ...               ...    ...   ...  ...
5921  BQ7     RAIN  31/01/2017 16:30    0.0    mm    P
5922  BQ7     RAIN  31/01/2017 16:45    0.0    mm    P
5923  BQ7     RAIN  31/01/2017 17:00    0.0    mm    P
5924  BQ7     RAIN  31/01/2017 17:15    0.0    mm    P
5925  BQ7     RAIN  31/01/2017 17:30    0.0    mm    P
5926  BQ7     RAIN  31/01/2017 17:45    0.0    mm    P
5927  BQ7     RAIN  31/01/2017 18:00    0.0    mm    P
5928  BQ7     RAIN  31/01/2017 18:15    0.0    mm    P
5929  BQ7     RAIN  31/01/2017 18:30    0.0    mm    P
5930  BQ7     RAIN  31/01/2017 18:45    0.0    mm    P
5931  BQ7     RAIN  31/01/2017 19:00    0.0    mm    P
5932  BQ7     RAIN  31/01/2017 19:15    0.0    mm    P
5933  BQ7     RAIN  31/01/2017 19:30    0.0    mm    P
5934  BQ7     RAIN  31/01/2017 19:45    0.0    mm    P
5935  BQ7     RAIN  31/01/2017 20:00    2.0    mm    P
5936  BQ7     RAIN  31/01/2017 20:15    2.0    mm    P
5937  BQ7     RAIN  31/01/2017 20:30    2.0    mm    P
5938  BQ7     RAIN  31/01/2017 20:45    2.0    mm    P
5939  BQ7     RAIN  31/01/2017 21:00    8.0    mm    P
5940  BQ7     RAIN  31/01/2017 21:15    8.0    mm    P
5941  BQ7     RAIN  31/01/2017 21:30    8.0    mm    P
5942  BQ7     RAIN  31/01/2017 21:45    8.0    mm    P
5943  BQ7     RAIN  31/01/2017 22:00    4.0    mm    P
5944  BQ7     RAIN  31/01/2017 22:15    4.0    mm    P
5945  BQ7     RAIN  31/01/2017 22:30    4.0    mm    P
5946  BQ7     RAIN  31/01/2017 22:45    4.0    mm    P
5947  BQ7     RAIN  31/01/2017 23:00    2.0    mm    P
5948  BQ7     RAIN  31/01/2017 23:15    2.0    mm    P
5949  BQ7     RAIN  31/01/2017 23:30    2.0    mm    P
5950  BQ7     RAIN  31/01/2017 23:45    2.0    mm    P

[5951 rows x 6 columns]

16. What is the average value of rainfall (enter your written answer in cell below your code, you will need to change the cell type to markdown), does this value seem reasonable?

In [45]:
df1.loc[:,'value'].mean()

1.6703093476798925

Yes the average value of ranfall seems to be reasonable

17. What is the minimum value of rainfall (enter your written answer in cell below your code, you will need to change the cell type to markdown), does this value seem reasonable?

In [46]:
df1.loc[:,'value'].min()

-1.0

No the minimum value of rainfall does not seem to be reasonable as the rainfall can not be negative

18. What is the maximum value of rainfall (enter your written answer in cell below your code, you will need to change the cell type to markdown), does this value seem reasonable?

In [47]:
df1.loc[:,'value'].max()

2000.0

Yes the value of maximum rainfall seems to be reasonable

19. Write the required python code to discover if there are any missing values in the rain dataset.

In [48]:
df1.isnull()

       site  variable   date  value  units   type
0     False     False  False  False  False  False
1     False     False  False  False  False  False
2     False     False  False  False  False  False
3     False     False  False  False  False  False
4     False     False  False  False  False  False
5     False     False  False  False  False  False
6     False     False  False  False  False  False
7     False     False  False  False  False  False
8     False     False  False  False  False  False
9     False     False  False  False  False  False
10    False     False  False  False  False  False
11    False     False  False  False  False  False
12    False     False  False  False  False  False
13    False     False  False  False  False  False
14    False     False  False  False  False  False
15    False     False  False  False  False  False
16    False     False  False  False  False  False
17    False     False  False  False  False  False
18    False     False  False  False  False  False
19    False     False  False  False  False  False
20    False     False  False  False  False  False
21    False     False  False  False  False  False
22    False     False  False  False  False  False
23    False     False  False  False  False  False
24    False     False  False  False  False  False
25    False     False  False  False  False  False
26    False     False  False  False  False  False
27    False     False  False  False  False  False
28    False     False  False  False  False  False
29    False     False  False  False  False  False
...     ...       ...    ...    ...    ...    ...
5921  False     False  False  False  False  False
5922  False     False  False  False  False  False
5923  False     False  False  False  False  False
5924  False     False  False  False  False  False
5925  False     False  False  False  False  False
5926  False     False  False  False  False  False
5927  False     False  False  False  False  False
5928  False     False  False  False  False  False
5929  False     False  False  False  False  False
5930  False     False  False  False  False  False
5931  False     False  False  False  False  False
5932  False     False  False  False  False  False
5933  False     False  False  False  False  False
5934  False     False  False  False  False  False
5935  False     False  False  False  False  False
5936  False     False  False  False  False  False
5937  False     False  False  False  False  False
5938  False     False  False  False  False  False
5939  False     False  False  False  False  False
5940  False     False  False  False  False  False
5941  False     False  False  False  False  False
5942  False     False  False  False  False  False
5943  False     False  False  False  False  False
5944  False     False  False  False  False  False
5945  False     False  False  False  False  False
5946  False     False  False  False  False  False
5947  False     False  False  False  False  False
5948  False     False  False  False  False  False
5949  False     False  False  False  False  False
5950  False     False  False  False  False  False

[5951 rows x 6 columns]

20. How many rows have missing values? You will need two cells, one for required python code and a second one converted to markdown to write your answer.

In [49]:
df1.isnull().sum()

site        0
variable    0
date        0
value       3
units       0
type        0
dtype: int64

There are three rows with missing the values in 'value' column

21. Write the rquired python code to remove the rows with missing values.

In [50]:
df1.dropna(how='any')

     site variable              date  value units type
0     BG1     RAIN  01/01/2017 00:15    0.0    mm    P
1     BG1     RAIN  01/01/2017 00:30    0.0    mm    P
2     BG1     RAIN  01/01/2017 00:45    0.0    mm    P
3     BG1     RAIN  01/01/2017 01:00    0.0    mm    P
4     BG1     RAIN  01/01/2017 01:15    0.0    mm    P
5     BG1     RAIN  01/01/2017 01:30    0.0    mm    P
6     BG1     RAIN  01/01/2017 01:45    0.0    mm    P
7     BG1     RAIN  01/01/2017 02:00    0.0    mm    P
8     BG1     RAIN  01/01/2017 02:15    0.0    mm    P
9     BG1     RAIN  01/01/2017 02:30    0.0    mm    P
10    BG1     RAIN  01/01/2017 02:45    0.0    mm    P
11    BG1     RAIN  01/01/2017 03:00    0.0    mm    P
12    BG1     RAIN  01/01/2017 03:15    0.0    mm    P
13    BG1     RAIN  01/01/2017 03:30    0.0    mm    P
14    BG1     RAIN  01/01/2017 03:45    0.0    mm    P
15    BG1     RAIN  01/01/2017 04:00    0.0    mm    P
16    BG1     RAIN  01/01/2017 04:15    0.0    mm    P
17    BG1     RAIN  01/01/2017 04:30    0.0    mm    P
18    BG1     RAIN  01/01/2017 04:45    0.0    mm    P
19    BG1     RAIN  01/01/2017 05:00    0.0    mm    P
20    BG1     RAIN  01/01/2017 05:15    0.0    mm    P
21    BG1     RAIN  01/01/2017 05:30    0.0    mm    P
22    BG1     RAIN  01/01/2017 05:45    0.0    mm    P
23    BG1     RAIN  01/01/2017 06:00    0.0    mm    P
24    BG1     RAIN  01/01/2017 06:15    0.0    mm    P
25    BG1     RAIN  01/01/2017 06:30    0.0    mm    P
26    BG1     RAIN  01/01/2017 06:45    0.0    mm    P
27    BG1     RAIN  01/01/2017 07:00    0.0    mm    P
28    BG1     RAIN  01/01/2017 07:15    0.0    mm    P
29    BG1     RAIN  01/01/2017 07:30    0.0    mm    P
...   ...      ...               ...    ...   ...  ...
5921  BQ7     RAIN  31/01/2017 16:30    0.0    mm    P
5922  BQ7     RAIN  31/01/2017 16:45    0.0    mm    P
5923  BQ7     RAIN  31/01/2017 17:00    0.0    mm    P
5924  BQ7     RAIN  31/01/2017 17:15    0.0    mm    P
5925  BQ7     RAIN  31/01/2017 17:30    0.0    mm    P
5926  BQ7     RAIN  31/01/2017 17:45    0.0    mm    P
5927  BQ7     RAIN  31/01/2017 18:00    0.0    mm    P
5928  BQ7     RAIN  31/01/2017 18:15    0.0    mm    P
5929  BQ7     RAIN  31/01/2017 18:30    0.0    mm    P
5930  BQ7     RAIN  31/01/2017 18:45    0.0    mm    P
5931  BQ7     RAIN  31/01/2017 19:00    0.0    mm    P
5932  BQ7     RAIN  31/01/2017 19:15    0.0    mm    P
5933  BQ7     RAIN  31/01/2017 19:30    0.0    mm    P
5934  BQ7     RAIN  31/01/2017 19:45    0.0    mm    P
5935  BQ7     RAIN  31/01/2017 20:00    2.0    mm    P
5936  BQ7     RAIN  31/01/2017 20:15    2.0    mm    P
5937  BQ7     RAIN  31/01/2017 20:30    2.0    mm    P
5938  BQ7     RAIN  31/01/2017 20:45    2.0    mm    P
5939  BQ7     RAIN  31/01/2017 21:00    8.0    mm    P
5940  BQ7     RAIN  31/01/2017 21:15    8.0    mm    P
5941  BQ7     RAIN  31/01/2017 21:30    8.0    mm    P
5942  BQ7     RAIN  31/01/2017 21:45    8.0    mm    P
5943  BQ7     RAIN  31/01/2017 22:00    4.0    mm    P
5944  BQ7     RAIN  31/01/2017 22:15    4.0    mm    P
5945  BQ7     RAIN  31/01/2017 22:30    4.0    mm    P
5946  BQ7     RAIN  31/01/2017 22:45    4.0    mm    P
5947  BQ7     RAIN  31/01/2017 23:00    2.0    mm    P
5948  BQ7     RAIN  31/01/2017 23:15    2.0    mm    P
5949  BQ7     RAIN  31/01/2017 23:30    2.0    mm    P
5950  BQ7     RAIN  31/01/2017 23:45    2.0    mm    P

[5948 rows x 6 columns]

22. Write the required python code to convert the index from simple number to the date column, remove the date column.

In [51]:
df1 = df1.set_index('date',drop=True)
df1

                 site variable  value units type
date
01/01/2017 00:15  BG1     RAIN    0.0    mm    P
01/01/2017 00:30  BG1     RAIN    0.0    mm    P
01/01/2017 00:45  BG1     RAIN    0.0    mm    P
01/01/2017 01:00  BG1     RAIN    0.0    mm    P
01/01/2017 01:15  BG1     RAIN    0.0    mm    P
01/01/2017 01:30  BG1     RAIN    0.0    mm    P
01/01/2017 01:45  BG1     RAIN    0.0    mm    P
01/01/2017 02:00  BG1     RAIN    0.0    mm    P
01/01/2017 02:15  BG1     RAIN    0.0    mm    P
01/01/2017 02:30  BG1     RAIN    0.0    mm    P
01/01/2017 02:45  BG1     RAIN    0.0    mm    P
01/01/2017 03:00  BG1     RAIN    0.0    mm    P
01/01/2017 03:15  BG1     RAIN    0.0    mm    P
01/01/2017 03:30  BG1     RAIN    0.0    mm    P
01/01/2017 03:45  BG1     RAIN    0.0    mm    P
01/01/2017 04:00  BG1     RAIN    0.0    mm    P
01/01/2017 04:15  BG1     RAIN    0.0    mm    P
01/01/2017 04:30  BG1     RAIN    0.0    mm    P
01/01/2017 04:45  BG1     RAIN    0.0    mm    P
01/01/2017 05:00  BG1     RAIN    0.0    mm    P
01/01/2017 05:15  BG1     RAIN    0.0    mm    P
01/01/2017 05:30  BG1     RAIN    0.0    mm    P
01/01/2017 05:45  BG1     RAIN    0.0    mm    P
01/01/2017 06:00  BG1     RAIN    0.0    mm    P
01/01/2017 06:15  BG1     RAIN    0.0    mm    P
01/01/2017 06:30  BG1     RAIN    0.0    mm    P
01/01/2017 06:45  BG1     RAIN    0.0    mm    P
01/01/2017 07:00  BG1     RAIN    0.0    mm    P
01/01/2017 07:15  BG1     RAIN    0.0    mm    P
01/01/2017 07:30  BG1     RAIN    0.0    mm    P
...               ...      ...    ...   ...  ...
31/01/2017 16:30  BQ7     RAIN    0.0    mm    P
31/01/2017 16:45  BQ7     RAIN    0.0    mm    P
31/01/2017 17:00  BQ7     RAIN    0.0    mm    P
31/01/2017 17:15  BQ7     RAIN    0.0    mm    P
31/01/2017 17:30  BQ7     RAIN    0.0    mm    P
31/01/2017 17:45  BQ7     RAIN    0.0    mm    P
31/01/2017 18:00  BQ7     RAIN    0.0    mm    P
31/01/2017 18:15  BQ7     RAIN    0.0    mm    P
31/01/2017 18:30  BQ7     RAIN    0.0    mm    P
31/01/2017 18:45  BQ7     RAIN    0.0    mm    P
31/01/2017 19:00  BQ7     RAIN    0.0    mm    P
31/01/2017 19:15  BQ7     RAIN    0.0    mm    P
31/01/2017 19:30  BQ7     RAIN    0.0    mm    P
31/01/2017 19:45  BQ7     RAIN    0.0    mm    P
31/01/2017 20:00  BQ7     RAIN    2.0    mm    P
31/01/2017 20:15  BQ7     RAIN    2.0    mm    P
31/01/2017 20:30  BQ7     RAIN    2.0    mm    P
31/01/2017 20:45  BQ7     RAIN    2.0    mm    P
31/01/2017 21:00  BQ7     RAIN    8.0    mm    P
31/01/2017 21:15  BQ7     RAIN    8.0    mm    P
31/01/2017 21:30  BQ7     RAIN    8.0    mm    P
31/01/2017 21:45  BQ7     RAIN    8.0    mm    P
31/01/2017 22:00  BQ7     RAIN    4.0    mm    P
31/01/2017 22:15  BQ7     RAIN    4.0    mm    P
31/01/2017 22:30  BQ7     RAIN    4.0    mm    P
31/01/2017 22:45  BQ7     RAIN    4.0    mm    P
31/01/2017 23:00  BQ7     RAIN    2.0    mm    P
31/01/2017 23:15  BQ7     RAIN    2.0    mm    P
31/01/2017 23:30  BQ7     RAIN    2.0    mm    P
31/01/2017 23:45  BQ7     RAIN    2.0    mm    P

[5951 rows x 5 columns]

23. Write the required python code to write out new cleaned dataset with the file name "london-rain-clean.csv".

In [53]:
df.to_csv("london-rain-clean.csv")